name: "Set up poetry env"
description: "Set up poetry env"

inputs:
  path:
    description: 'Who to greet'
    required: true

runs:
  using: "composite"
  steps:
    - uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        cache: 'pip'

    - name: move
      shell: bash
      run: cd ${{ inputs.path }}

    - name: Install dependencies
      shell: bash
      working-directory: ${{ inputs.path }}
      run: |
        pip install poetry==1.5.1
        poetry install --with dev
