name: "Linting with ruff"
description: "Linting with ruff"

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4

    - uses: ./.github/actions/python-env

    - name: Lint with Ruff
      run: poetry run ruff --output-format=github .
