name: Advent Of Code 2023

on: [push]

jobs:


  check:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./aoc2023

    steps:
      - uses: actions/checkout@v4

      - uses: .github/actions/check
