name: Advent Of Code 2023

on: [push]

jobs:
  check-and-test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./aoc2023

    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/check
        with:
          path: "./aoc2023"

      - uses: ./.github/actions/test
        with:
          path: "./aoc2023"

  build-and-deploy:
    runs-on: ubuntu-latest

    needs: [check-and-test]

    defaults:
      run:
        working-directory: ./aoc2023

    steps:
      - name: Download coverage
        uses: actions/download-artifact@v3
        with:
          name: .coverage
          path: "./aoc2023"

      - name: Create build folder
        run: ls

      - uses: tj-actions/coverage-badge-py@v2
        name: Generate coverage badge
        with:
          working-directory: ./aoc2023
          output: ./build/coverage.svg

      - name: Publish coverage report to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: ./aoc2023/build/
