name: Advent Of Code 2023

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]
    defaults:
      run:
        working-directory: ./aoc2023

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        cache: 'pip'

    - name: Install dependencies
      run: |
        pip install poetry==1.5.1
        poetry install --with dev

    - name: Lint with Ruff
      run: poetry run ruff --output-format=github .

    - name: Test with pytest
      run: poetry run pytest --junitxml=junit/test-results.xml --cov=. --cov-report=xml --cov-report=html --cov-fail-under=95

    - name: Create build folder
      run: mkdir -p build

    - uses: tj-actions/coverage-badge-py@v2
      name: Generate coverage badge
      with:
        working-directory: ./aoc2023
        output: ./build/coverage.svg

    - name: Publish coverage report to GitHub Pages
#      if: ${{ github.ref == 'refs/heads/master' }}
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: ./build/
